from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent

DOCS_DIR = PROJECT_ROOT / "docs"
GUIDES_DIR = DOCS_DIR / "guides"
REFERENCES_DIR = DOCS_DIR / "references"
RELATED_WORKS_DIR = REFERENCES_DIR / "related_works"
EXAMPLES_DIR = REFERENCES_DIR / "examples"

MANUSCRIPT_DIR = PROJECT_ROOT / "manuscript"
DRAFTS_DIR = MANUSCRIPT_DIR / "drafts"
SUBMISSION_DIR = MANUSCRIPT_DIR / "submission"

DATA_DIR = PROJECT_ROOT / "data"
LEGACY_DATA_DIR = DATA_DIR / "legacy"
LEGACY_GRAPHS_DIR = LEGACY_DATA_DIR / "graphs"

RESULTS_DIR = PROJECT_ROOT / "results"
RAW_RESULTS_DIR = RESULTS_DIR / "raw"
ANALYSIS_RESULTS_DIR = RESULTS_DIR / "analysis"
TABLE_RESULTS_DIR = RESULTS_DIR / "tables"
FIGURE_RESULTS_DIR = RESULTS_DIR / "figures"
EXPLORATORY_FIGURES_DIR = FIGURE_RESULTS_DIR / "exploratory"
PAPER_FIGURES_DIR = FIGURE_RESULTS_DIR / "paper"

